kubernetes-ingress:
  controller:
    kind: DaemonSet
    daemonset:
      useHostPort: true
      hostPorts:
        http: 80
        https: 443
        stat: 1024

    service:
      enabled: false

    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule

    ingressClassResource:
      name: haproxy-internal
      default: true
    ingressClass: haproxy-internal
