kubernetes-ingress:
  controller:
    kind: DaemonSet
    service:
      nodePorts:
        http: 30001
        https: 30002
        stat: 30003
        prometheus: 30004
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
