kubernetes-ingress:
  controller:
    service:
      nodePorts:
        http: 80
        https: 443
        stat: 30003
        prometheus: 30004

    nodeSelector:
      node-role.kubernetes.io/control-plane: ''
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule

    ingressClassResource:
      name: haproxy-internal
      default: true
    ingressClass: haproxy-internal

    autoscaling:
      enabled: true
      minReplicas: 1
      targetCPUUtilizationPercentage: 50
